### ISSUE TITLE
bug: Mf6Splitter import error

### ISSUE THREAD

**Issue by robinkeegan** [modflowpy/flopy#1995]
Attempting to reproduce the tutorial using the model splitter: https://flopy.readthedocs.io/en/latest/Notebooks/mf6_parallel_model_splitting_example.html 
I get an error `ImportError: cannot import name 'Mf6Splitter' from 'flopy.mf6.utils'`
When running the line:
`from flopy.mf6.utils import Mf6Splitter`
Has the MF6Splitter function changed it's import location?
I am working on windows 11 using FloPy 3.3.6.

**Comment by jlarsen-usgs** [comment]
@robinkeegan 
The `Mf6Spitter` utility was added to FloPy in version 3.4.0. If you update your flopy installation:

`pip install -U flopy`

you should have access to the model splitter and be able to run to notebook.
