### PR TITLE
support for copy.copy() and copy.deepcopy() with python 3.5+

### PR DESCRIPTION
**Pull request by aleaf**
Changes to attribute handling that allow most flopy object instances to be copied with `copy.deepcopy()`. Mostly resolves issue #591, except for the caveats that @spaulins-usgs [mentioned](https://github.com/modflowpy/flopy/issues/591). Copying may work in python 2.7 but is not supported.

### CODE REVIEW

**Comment by langevin-usgs** [comment]
Hi @aleaf, it looks like there were a few failures.  I restarted the ones that appeared to be strange hiccups, but this 3.5 error looks like something related to this copy change that you made:

```
======================================================================
ERROR: t066_test_copy.test_mf6_copy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 207, in test_mf6_copy
    assert model_is_copy(m, m_dc)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 32, in model_is_copy
    m2packages = get_package_list(m2)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 18, in get_package_list
    packages = [p.name[0].upper() for p in model.packagelist]
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 18, in <listcomp>
    packages = [p.name[0].upper() for p in model.packagelist]
  File "/home/travis/build/modflowpy/flopy/flopy/mf6/mfpackage.py", line 1240, in name
    return [self.package_name]
AttributeError: 'ModflowUtlobs' object has no attribute 'package_name'
```

**Comment by aleaf** [comment]
@langevin-usgs I don't understand this error with python 3.5. It isn't consistent ([the same build just passed on my fork](https://travis-ci.com/aleaf/flopy/jobs/247880675)), and I couldn't reproduce it locally.

**Comment by langevin-usgs** [comment]
@aleaf, are you up to date with develop?  @jlarsen-usgs made some recent changes to obs, if I remember correctly.

**Comment by aleaf** [comment]
yup, just rebased to it prior to pushing to getattr_issue

**Comment by langevin-usgs** [comment]
Ha!  Must have been a gremlin.  Looks like it works now...

**Comment by langevin-usgs** [comment]
@aleaf-usgs, it looks like something is smoldering in here.  We are having intermittent failures with 3.5 on Travis.  Please keep an eye out on this.  

```
======================================================================
ERROR: t066_test_copy.test_mf6_copy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 207, in test_mf6_copy
    assert model_is_copy(m, m_dc)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 32, in model_is_copy
    m2packages = get_package_list(m2)
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 18, in get_package_list
    packages = [p.name[0].upper() for p in model.packagelist]
  File "/home/travis/build/modflowpy/flopy/autotest/t066_test_copy.py", line 18, in <listcomp>
    packages = [p.name[0].upper() for p in model.packagelist]
  File "/home/travis/build/modflowpy/flopy/flopy/mf6/mfpackage.py", line 1240, in name
    return [self.package_name]
AttributeError: 'ModflowUtlobs' object has no attribute 'package_name'
```

**Comment by aleaf** [comment]
@langevin-usgs, this seems like an issue with MODFLOW 6 packages (under some condition with python 3.5, instances of the above type of package don’t have a name attribute like all of the other package subclasses). @spaulins-usgs, any idea what might be causing this?

**Comment by spaulins-usgs** [comment]
@aleaf Not sure why this is happening. ModflowUtlobs inherits from MFPackage which initializes self.package_name. I am not sure why it isn't being copied. My guess is it has something to do with the obs package being a "subpackage" of other packages. As a subpackage the obs package is an attribute of its parent package. Maybe copy gets confused when copying an object that is contained in another object but also shares the same inheritance tree as the object that contains it.

**Comment by mwtoews** [comment]
I can reproduce this error with Python 3.5. It happens either sporadically with each python start-up, or always with `export PYTHONHASHSEED=0`, which [disables hash randomization](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED). The deepcopy object `m_dc.sfr_obs.__dict__.keys()` has only a subset of items as the original package object, indicating that only a partial copy was done. This is likely a Python 3.5 bug. I can't seem to get the same behaviour with Python 3.6, so I'd suggest bumping this feature to Python 3.6+ support. I haven't made a PR for this, but you can see this suggested commit as a potential "fix" 2aca943e7a1bab1bb3ca0adeccfd6d57ef01b103
